#!/usr/bin/env python3
# gen.py: generate every asset in MANIFEST that does not exist yet, log cost per image.
import base64, json, pathlib, sys, time, urllib.request, urllib.error
sys.path.insert(0, '/Users/ls/Claude-Workspace/personal/imagegen')
from costlog import record
HERE = pathlib.Path(__file__).resolve().parent
KEY = next(l.split('=', 1)[1].strip() for l in open('/Users/ls/Claude-Workspace/personal/.env') if l.startswith('OPENAI_API_KEY='))
STYLE = "Hand-painted stylized medieval fantasy game art in the style of premium tower defense games such as Kingdom Rush: chunky simplified forms, one bold readable silhouette, thick soft painterly shading, warm torchlight key light from the upper left with a cool blue-grey shadow side, saturated but harmonious colours built on grey castle stone, aged oak, iron, heraldic crimson and gold, a thin dark outline around the whole silhouette, crisp clean edges, high detail on the focal point and calm simple large shapes elsewhere. No text, no letters, no watermark, no frame, no border, nothing cut off at the edges."
MANIFEST = [  # (filename, subject sentence, size, transparent)
    ("icon-thorn.png", "A wooden ballista turret with an iron-tipped bolt loaded, oak and amber tones. Broad crossbow arms, one clearly visible long bolt and a stout wooden turret support. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-sap.png", "A round stone-rimmed tar pit, black bubbling tar with a teal-green sheen, one sticky drip on the rim. The dark tar surface is a broad clear shape inside a low rim of chunky grey stones. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-bloom.png", "A wooden catapult with a red-painted throwing arm and a basket of grey stones. A compact oak siege engine with a strong triangular support and a clearly raised crimson throwing arm, distinct from a crossbow. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-prism.png", "A slender grey stone mage spire topped with a glowing violet crystal orb. A simple tapered stone tower and a large luminous faceted violet sphere, its compact glow contained near the orb. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-hedge.png", "A square palisade block of sharpened timber stakes bound with rope. Stout aged oak logs packed into a compact square defensive block, pointed tops and two bold rope bindings. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-ember.png", "An iron fire brazier on a stone base, orange flames, glowing coals. A dark iron bowl holding one bold orange flame silhouette with a golden hot centre, over a compact grey stone foot. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-lantern.png", "A war banner: a tall pole with a crimson and gold heraldic banner and a gilded finial. A broad crimson cloth with a simple gold crown heraldic emblem, gold edging and readable large folds, attached to one stout pole with a pointed gold finial. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-wood.png", "A small stack of three cut oak logs, warm bark, axe marks. Exactly three stout logs stacked two below and one above with pale golden cut ends and simple broad bark ridges. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-rock.png", "A chunky grey quarried stone block with chisel facets and a chip broken off. A roughly cuboid block with large planar grey faces, a visibly chipped lower corner and its small chip tucked against the block. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-iron.png", "A dark steel-blue forged iron ingot with hammer marks and a cold sheen. A single broad trapezoidal metal ingot with a few shallow hammered dents and calm blue-grey metallic faces. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-diamond.png", "A cut cyan diamond gem, bright facets, one sparkle. A single broad brilliant-cut cyan gemstone with a pointed bottom and large clean facets, one tiny white sparkle touching its upper left edge. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-coin.png", "A round gold coin with a crown embossed on it, thick rim. One upright coin tilted just enough to reveal its thick edge, a single large simple crown relief and broad warm gold faces. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("icon-life.png", "A glossy crimson heart on a small heraldic shield with a gold rim. A large raised red heart covering most of a compact medieval heater shield, with a narrow dark iron backing and thick gold rim, clearly one combined emblem. Medieval game UI emblem that reads immediately at 32 pixels, one object with chunky simple shapes and slight bottom weight, no background disc or scenery. Front three-quarter view, slightly from above. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
]
def gen(name, subject, size, transparent):
    out = HERE / name
    if out.exists(): return
    body = {"model": "gpt-image-2", "prompt": STYLE + " " + subject, "size": size,
            "quality": "high", "output_format": "png", "n": 1}
    if transparent: body["background"] = "transparent"
    req = urllib.request.Request("https://api.openai.com/v1/images/generations",
        data=json.dumps(body).encode(), headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=300) as r: payload = json.load(r)
            break
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503) and attempt < 4: time.sleep(10 * (attempt + 1)); continue
            raise
    out.write_bytes(base64.b64decode(payload["data"][0]["b64_json"]))
    (HERE / 'prompts' / (out.stem + '.txt')).write_text(STYLE + " " + subject)
    record(HERE, name, provider="openai", model="gpt-image-2", usage=payload.get("usage"))
    print("wrote", name, flush=True)
(HERE / 'prompts').mkdir(exist_ok=True)
for item in MANIFEST: gen(*item)
