#!/usr/bin/env python3
# gen.py: generate every asset in MANIFEST that does not exist yet, log cost per image.
import base64, json, pathlib, sys, time, urllib.request, urllib.error
sys.path.insert(0, '/Users/ls/Claude-Workspace/personal/imagegen')
from costlog import record
HERE = pathlib.Path(__file__).resolve().parent
KEY = next(l.split('=', 1)[1].strip() for l in open('/Users/ls/Claude-Workspace/personal/.env') if l.startswith('OPENAI_API_KEY='))
STYLE = "Hand-painted stylized medieval fantasy game art in the style of premium tower defense games such as Kingdom Rush: chunky simplified forms, one bold readable silhouette, thick soft painterly shading, warm torchlight key light from the upper left with a cool blue-grey shadow side, saturated but harmonious colours built on grey castle stone, aged oak, iron, heraldic crimson and gold, a thin dark outline around the whole silhouette, crisp clean edges, high detail on the focal point and calm simple large shapes elsewhere. No text, no letters, no watermark, no frame, no border, nothing cut off at the edges."
MANIFEST = [  # (filename, subject sentence, size, transparent)
    ("enemy-grub.png", "A squat green goblin footsoldier with a rusty blade and a leather cap, marching. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic overhead game sprite: the top of the cap, broad shoulders and back are visible, nose and blade face north, feet trail south; no front-facing portrait or tilted camera. Stocky compact body, wide pointed ears, short sturdy legs, one chunky rusty blade held beside him, simple leather kit. Bright moss-green skin is the one strong colour accent. The body fills about 70 percent of the frame and all weapon tips stay fully inside with clear margin. Strong silhouette and calm large painted shapes readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-runner.png", "A lean grey wolf mid sprint with a small goblin rider clinging to its back, motion streaks. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic overhead game sprite: long narrow wolf silhouette with ears and pointed muzzle at twelve o'clock, the spine runs vertically and the tail trails toward six o'clock. Four legs stretched in a sprint. The small green goblin crouches low on the wolf's back and faces the same northward direction. The tops of heads and backs are visible, not a side profile or front portrait. Grey fur and simple dark leather saddle; the rider's bright green skin is the single bold accent. Only a few short restrained motion streaks trail behind. The body fills about 70 percent of the frame and ears, paws, tail and streaks stay fully inside. Strong silhouette readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-armor.png", "A heavy knight in dark plate armour with a great shield and a closed helm, slow and solid. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. This is a strict 90-degree overhead dorsal game token, viewed from above and behind as the knight walks AWAY toward the TOP edge. Show the BACK and TOP of the helmet, tops of massive shoulder plates, and armoured BACK. The FACE, visor, chest and front of the torso are completely hidden on the far north side. The rounded back of the helmet is at upper centre, the shoulders span horizontally below it, a short broad back and small trailing heels sit below; extreme overhead foreshortening, not a standing character portrait. A huge iron shield lies along one side, its upper edge points north and its pointed bottom trails south. Dark blue-grey iron, one plain small crimson inset on the shield, no elaborate heraldry. Chunky calm forms, compact weighty silhouette. The body fills only about 70 percent of the frame with generous transparent margins. Readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-moth.png", "A grey stone gargoyle with bat wings spread wide, glowing eyes, flying. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic dorsal overhead view: horned head and north-pointing snout at twelve o'clock, grey carved-stone back in the centre, two broad bat wings extended left and right, clawed feet and a short tail trailing south. The eyes give the one bright amber accent. Large calm slate-grey wing membranes with simple angular stone ribs; compact muscular body. No front-facing portrait and no oblique camera. The body and wings form a strong broad silhouette filling about 70 percent of the frame; wing tips have clear transparent margin and nothing is cropped. Instantly readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-brood.png", "A wooden goblin war wagon with iron-rimmed wheels, three whelps peeking out, ready to burst open. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic overhead plan view of one self-contained squat rectangular open-top war wagon rolling north. The wagon's front and all three goblin heads point toward twelve o'clock. Exactly three small green goblin whelps peek from the open wooden bed, the tops of their heads and pointed ears visible from above. Four broad iron-rimmed wheels visible as side protrusions, chunky aged oak planks and bent iron bands suggest a wagon ready to break open. Green goblin heads are the one bright accent. No animal pulling it, no separate props, no front elevation or angled camera. The body fills about 70 percent of the frame, every wheel safely inside the image. Strong boxy silhouette readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-grubling.png", "A tiny goblin whelp with a dagger, round and quick, big eyes, clearly the goblin's runt. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic overhead game sprite: oversized round bald lime-green head near the upper part of the silhouette, wide pointed ears, tiny round torso in a simple brown rag, short quick legs trailing south. A single short chunky iron dagger is clutched beside it. The top of the head and back are visible and the little nose points north; large eyes peek at the forward edge of the head, never looking upward at the viewer. No cap or armour, so it is clearly the bareheaded runt of the stocky goblin footsoldier. Lime-green skin is the one bright accent. No front-facing portrait or angled camera. The body fills about 70 percent of the frame and every ear and dagger tip has clear margin. Simple playful rounded silhouette readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-warden.png", "A tall paladin in white and gold plate with a glowing holy shield aura around him, a warhammer. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. This is a strict 90-degree overhead dorsal game token, viewed from above and behind as the paladin walks AWAY toward the TOP edge. Show the BACK and TOP of his white helmet, the top surfaces of white shoulder plates, and his gold-trimmed white armoured BACK. His FACE, visor, chest and front of torso are completely hidden on the far north side. The smooth back of his helmet is at upper centre, shoulders span below it, a short foreshortened back and plain trailing white cape run south. A chunky warhammer is held at one side, with a compact shield at the other side. A thin gold shield-shaped holy aura surrounds him with transparent space between the body and aura, the whole aura fully inside the image with at least 100 pixels of empty margin. White and cool grey plate, gold is the only bright accent. The body fills about 70 percent of the frame. Strong noble silhouette readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("enemy-boss.png", "A huge orc warlord with a horned iron crown, a two-handed axe, a tattered war banner on his back, glowing eyes. Seen from directly above, looking straight down, the creature centred, head pointing to the top of the frame, soft drop shadow. Strict orthographic dorsal overhead game sprite: horned crown and broad north-pointing orc head near twelve o'clock, massive shoulders and hunched armoured back, wide planted feet trailing south. Muted olive-grey skin, dark iron armour and a huge double-headed two-handed axe held across the front. One tattered heraldic crimson war banner fixed to his back trails toward six o'clock without obscuring his head. Small crimson eye glows echo the banner as the one strong accent colour. The top of the crown and shoulders are clearly visible, no upright frontal portrait or oblique camera. The broad body fills about 70 percent of the frame and crown horns, axe and banner stay fully inside with clear margins. The largest and most imposing silhouette, readable at 40 px. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
]
def gen(name, subject, size, transparent):
    out = HERE / name
    if out.exists(): return
    body = {"model": "gpt-image-2", "prompt": STYLE + " " + subject, "size": size,
            "quality": "high", "output_format": "png", "n": 1}
    if transparent: body["background"] = "transparent"
    req = urllib.request.Request("https://api.openai.com/v1/images/generations",
        data=json.dumps(body).encode(), headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=300) as r: payload = json.load(r)
            break
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503) and attempt < 4: time.sleep(10 * (attempt + 1)); continue
            raise
    out.write_bytes(base64.b64decode(payload["data"][0]["b64_json"]))
    (HERE / 'prompts' / (out.stem + '.txt')).write_text(STYLE + " " + subject)
    record(HERE, name, provider="openai", model="gpt-image-2", usage=payload.get("usage"))
    print("wrote", name, flush=True)
(HERE / 'prompts').mkdir(exist_ok=True)
for item in MANIFEST: gen(*item)
