#!/usr/bin/env python3
# gen.py: generate every asset in MANIFEST that does not exist yet, log cost per image.
import base64, json, pathlib, sys, time, urllib.request, urllib.error
sys.path.insert(0, '/Users/ls/Claude-Workspace/personal/imagegen')
from costlog import record
HERE = pathlib.Path(__file__).resolve().parent
KEY = next(l.split('=', 1)[1].strip() for l in open('/Users/ls/Claude-Workspace/personal/.env') if l.startswith('OPENAI_API_KEY='))
STYLE = "Hand-painted stylized medieval fantasy game art in the style of premium tower defense games such as Kingdom Rush: chunky simplified forms, one bold readable silhouette, thick soft painterly shading, warm torchlight key light from the upper left with a cool blue-grey shadow side, saturated but harmonious colours built on grey castle stone, aged oak, iron, heraldic crimson and gold, a thin dark outline around the whole silhouette, crisp clean edges, high detail on the focal point and calm simple large shapes elsewhere. No text, no letters, no watermark, no frame, no border, nothing cut off at the edges."
MANIFEST = [  # (filename, subject sentence, size, transparent)
    ("tile-meadow-a.png", "Worn grey-green castle bailey ground seen from directly above: trampled grass over flagstones, even tone. A quiet playable ground surface, orthographic overhead, with small shallow irregular stone fragments partially hidden under short flattened grass. Muted medium grey-green with cool grey stones and grey olive soil, all close in value. Uniformly distributed small ground details without clumps, large patches or a central highlight. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("tile-meadow-b.png", "Worn grey-green castle bailey ground seen from directly above: trampled grass over flagstones, a touch more flagstone showing, same even tone. A quiet playable ground surface, orthographic overhead, with small shallow irregular stone fragments partially hidden under short flattened grass. Muted medium warm grey-green with neutral grey stones and grey olive soil, all close in value. Match a uniform average ground tone of approximately RGB 89, 91, 74, hex #595b4a. This warm grey olive midtone dominates the entire texture, with very restrained local highlights and shadows. Avoid a blue or cold dark green cast. Uniformly distributed small ground details without clumps, large patches or a central highlight. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("tile-meadow-c.png", "Worn grey-green castle bailey ground seen from directly above: trampled grass over flagstones with a few small pebbles, same even tone. A quiet playable ground surface, orthographic overhead, with small shallow irregular stone fragments partially hidden under short flattened grass. Muted medium grey-green with cool grey stones and grey olive soil, all close in value. Uniformly distributed small ground details without clumps, large patches or a central highlight. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("tile-path.png", "A trodden dirt siege road seen from directly above, cart ruts, small stones, dark earth. Orthographic overhead ground material, muted dark umber with cool grey pebble flecks, compacted earth and two subtle parallel shallow wheel ruts running vertically all the way through the image. Uniform road surface across the full square, with no road verge or grass border. Broad calm painterly shapes and subdued contrast at game size. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("ground-outer.png", "Dark siege camp ground beyond the walls seen from directly above: mud, trampled grass, scattered arrows and rubble, deep green and brown. Orthographic overhead ground material. Sparse small broken arrows and tiny grey castle rubble fragments distributed over dark flattened moss-green grass and muddy earth. A quiet continuous ground surface with no buildings, no large rubble heaps and no large pools. Low contrast small ground detail evenly distributed throughout. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("apron-wood.png", "Grey castle rampart stone seen from directly above: large mortared ashlar blocks with moss in the joints. Flat overhead masonry ground material with no wall sides and no perspective. Simple running bond of broad rectangular grey stone blocks. Exactly FOUR equally tall courses fill the entire square. Each course is one quarter of the image height and contains two broad blocks, with a half-block stagger on alternate courses. The top and bottom edges are both the middle of the same narrow horizontal mortar joint. Stop at the mortar joint immediately after the fourth full course. No fifth partial course, no thin stone strip at either image edge. Match the horizontal stone pattern and mortar at the left and right edges. Uniform grey midtone, restrained dark moss only inside the narrow mortar joints, softly painted stone grain. Equal diffuse neutral illumination replaces directional torchlight for this ground material. Seamless tileable texture, edges wrap perfectly, even flat lighting across the whole frame, no vignette, no single focal object, fills the whole frame.", "1024x1024", False),
    ("gate-entry.png", "The horde's camp gate: a dark timber and iron portcullis in a rough stone arch, torches, ominous. TRUE DIRECTLY OVERHEAD PLAN VIEW, camera exactly 90 degrees above the ground, as on a top-down battle map. Show the horizontal top faces of a compact low stone arch and two squat rough stone shoulders around a short north-south passage. Black iron portcullis and aged oak lintel cross the passage horizontally. Two small torches sit on the stone shoulders, seen as compact amber flame tops. Charcoal-grey rough stone, dark aged oak and black iron. No tall upright facade facing the viewer, no front elevation, no isometric or three-quarter camera, no visible horizon. Broad compact structure fitting within the central 80 percent of the canvas, with generous empty margins on every side. Self-contained structure, no landscape or ground tile beneath it, no detached effects. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("gate-exit.png", "The keep gate: an arched stone gatehouse with a crimson and gold banner and a glowing heart shield above the door. A small compact sprite centered within generous transparent padding: keep at least 120 pixels of completely empty canvas beyond the whole silhouette on ALL FOUR sides of this 1024 pixel square. The entire structure including shadows must be no more than 784 pixels wide. TRUE DIRECTLY OVERHEAD PLAN VIEW, camera exactly 90 degrees above the ground, as on a top-down battle map. Two squat pale grey circular stone watchtower tops are joined by the horizontal top of a low stone arch over a short north-south passage. Only a hint of wall depth, with horizontal top faces dominating and no tall tower facades. A small gold shield bearing a raised red heart is mounted flat on top of the arch lintel, facing the sky so it is clearly visible from directly above. A short crimson and gold banner is draped flat over the top stone beside the shield. Aged oak door with iron bands across the passage. Gentle localized golden glow on the heart shield. No upright front elevation, no isometric or three-quarter camera, no visible horizon. Zoom out enough to preserve the generous empty margin around BOTH round towers. Self-contained structure, no landscape or ground tile beneath it, no detached effects. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-tree-a.png", "A round leafy oak canopy seen from directly above, thick trunk shadow. Strict overhead orthographic camera, clustered chunky lobes of rich muted moss-green oak leaves with warm olive tips and cool blue-green shade, a little thick brown trunk visible through the middle. Broad readable round crown, compact shadow attached beneath the canopy, no grass patch or ground tile, no side elevation. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-tree-b.png", "A tall dark pine canopy seen from directly above. Strict overhead orthographic camera looking straight down the trunk, a compact radial starburst of layered dark evergreen boughs tapering to the central top, cool blue-green shadow and muted olive needle tips. A recognizably coniferous crown, no side elevation and no triangular upright tree, no grass patch or ground tile. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-tree-c.png", "A bare dead tree seen from directly above, twisted branches, a crow. Strict overhead orthographic camera looking straight down on a twisted grey-brown trunk and a radial branching crown of thick jagged leafless boughs. One small black crow perched on a branch with a readable beak. Broad clear branch silhouette, all branch tips inside the canvas, no grass patch or ground tile, no side elevation. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-rock-a.png", "A mossy grey boulder seen from directly above. Strict overhead orthographic camera, one chunky irregular cool grey castle-country boulder with broad softly painted facets, patches of dark moss-green on its creases and a thin attached contact shadow. No grass patch, no ground tile, no pedestal. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-rock-b.png", "A broken siege boulder split in two with rubble, seen from directly above. Strict overhead orthographic camera, two close-set chunky grey stone halves with a deep jagged split and a few small chips gathered against the base, rough fresh pale fracture faces and dark cool outer stone. One compact grouped prop with a bold broken outline, no ground tile or pedestal. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-flowers-a.png", "A canvas siege tent with a crimson pennant seen from directly above. Strict overhead orthographic camera, a single compact rectangular medieval wedge tent, warm weathered ivory canvas roof with two sloping roof panels meeting at an oak ridgepole, restrained rope lashings and a small crimson triangular pennant attached to the ridge. Readable canvas folds and crimson heraldic accent, no lettering, no ground tile, no perspective horizon. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-flowers-b.png", "A stack of wooden barrels and a hay bale seen from directly above. Strict overhead orthographic camera, a compact cluster of three aged oak barrels with dark iron hoops and round plank lids next to one rectangular golden straw bale tied with thick rope. Overlapping simplified forms with one cohesive silhouette, no ground tile or grass patch. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
    ("prop-stump.png", "A wooden cart wheel and a broken ladder seen from directly above. Strict overhead orthographic camera, a compact salvage pile of one aged oak spoked cart wheel with a dark iron rim overlapping a broken wooden ladder with four rough rungs, splintered ends and rope binding. Both lie flat with a strong readable combined outline, no ground tile or grass patch. Single object, centred, filling about 80 percent of the frame, isolated on a fully transparent background.", "1024x1024", True),
]
def gen(name, subject, size, transparent):
    out = HERE / name
    if out.exists(): return
    body = {"model": "gpt-image-2", "prompt": STYLE + " " + subject, "size": size,
            "quality": "high", "output_format": "png", "n": 1}
    if transparent: body["background"] = "transparent"
    req = urllib.request.Request("https://api.openai.com/v1/images/generations",
        data=json.dumps(body).encode(), headers={"Authorization": f"Bearer {KEY}", "Content-Type": "application/json"})
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=300) as r: payload = json.load(r)
            break
        except urllib.error.HTTPError as e:
            if e.code in (429, 500, 502, 503) and attempt < 4: time.sleep(10 * (attempt + 1)); continue
            raise
    out.write_bytes(base64.b64decode(payload["data"][0]["b64_json"]))
    (HERE / 'prompts' / (out.stem + '.txt')).write_text(STYLE + " " + subject)
    record(HERE, name, provider="openai", model="gpt-image-2", usage=payload.get("usage"))
    print("wrote", name, flush=True)
(HERE / 'prompts').mkdir(exist_ok=True)
for item in MANIFEST: gen(*item)
