import './style.css';
import {Game,TOWERS,STAGES,MATERIALS} from './game.js';
import {World} from './world.js';
const $=s=>document.querySelector(s),SAVE='undergrowth-save-v2';
let game;try{const raw=JSON.parse(localStorage.getItem(SAVE)||localStorage.getItem('undergrowth-save-v1'));game=[1,2].includes(raw?.version)&&Array.isArray(raw.towers)&&raw.stage>=0&&raw.stage<=10?new Game(raw):new Game()}catch{game=new Game()}
const mobileQuery=matchMedia('(max-width: 700px), (max-width: 1000px) and (pointer: coarse)');
let pendingPlacement=null;
let build='thorn',selected=null,paused=false,backgroundPause=null,speed=1,sound=false,toastTimer,saveTime=0,uiTime=0,last=performance.now(),audio;
$('#app').innerHTML=`<main class="game-shell">
  <div class="map-area"><section class="garden-strip" aria-label="Resource garden"><div class="garden-strip-heading"><h2>Garden</h2><p>Buy a resource. It collects itself. Upgrade with coins.</p></div><div id="garden-summary" class="garden-summary"></div><div id="farms" class="garden-plots"></div></section><section class="scene-wrap" id="scene" aria-label="Battlefield">
    <div class="map-status"><span>Stage <b id="stage-number">01</b><span class="status-muted"> / 10</span></span><span class="status-divider"></span><span class="heart">♥ <b id="lives">20 / 20</b></span></div>
    <div class="map-controls"><button id="pause" aria-label="Pause game" title="Pause · Space">Ⅱ</button><button id="speed" title="Game speed">1×</button><button id="zoom" class="mobile-only" aria-label="Zoom into battlefield">＋</button><button id="fit" class="mobile-only" aria-label="Fit battlefield">⤢</button><button id="mobile-options" class="mobile-only" aria-label="Game menu">⋯</button><button id="path" aria-pressed="true" title="Show enemy route">Route on</button></div>
    <div id="placement" class="placement" hidden><button id="cancel-place" aria-label="Cancel placement">×</button><button id="confirm-place">Place tower</button></div><div class="paused-overlay" id="paused" hidden>Paused</div>
  </section>
  </div><aside class="sidebar" aria-label="Build and garden">
    <div class="sidebar-heading"><span class="wordmark">undergrowth.</span><button id="help" class="icon-button" aria-label="How to play">?</button></div>
    <div class="resources"><span title="Coins"><i class="coin">◈</i><b id="coins">200</b><small>Coins</small></span></div>
    <div class="sidebar-scroll">
      <section class="defenses"><h2>Defenses <small>1–5</small></h2><div class="cards">${Object.entries(TOWERS).map(([id,t],i)=>`<button class="tower-card ${id==='thorn'?'selected':''}" data-build="${id}" title="${t.desc}" aria-pressed="${id==='thorn'}"><span class="tower-icon" style="--tile:${t.color}">${t.symbol}</span><span class="tower-summary"><b>${t.name}</b><span class="tower-description">${t.desc}</span></span><small>◈ ${t.cost}</small></button>`).join('')}</div><div id="detail" class="detail" hidden></div></section>
      <section class="garden inventory"><h2>Materials</h2>${MATERIALS.map(m=>`<div class="inventory-row"><span>${m.name}</span><b id="${m.id}">0</b></div>`).join('')}<p>Used to upgrade your towers.</p></section>
    </div>
    <div class="wave-controls"><div class="wave-meta"><span id="wave-counter">Wave 1 / 3</span><span id="enemy-counter">9 creatures</span></div><button class="primary" id="start">Begin wave ↗</button><div class="utilities"><span id="saved">Autosaved</span><div><button id="sound" aria-label="Enable sound" title="Sound">♪</button><button id="restart" aria-label="Start a new garden" title="New garden">↺</button></div></div></div>
  </aside>
</main><div id="toast" role="status" aria-live="polite"></div><dialog id="modal"></dialog><dialog id="garden-modal" class="garden-sheet"><div class="sheet-heading"><div><h2>Your garden</h2><p>Collects automatically while you defend.</p></div><button id="close-garden" aria-label="Close garden">×</button></div><div class="sheet-body"></div></dialog>`;
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function beep(freq=440){if(!sound)return;try{audio??=new AudioContext();const o=audio.createOscillator(),gain=audio.createGain();o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.5,audio.currentTime+.12);gain.gain.setValueAtTime(.025,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.14);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.15)}catch{}}
function persist(){try{localStorage.setItem(SAVE,game.serialize());$('#saved').textContent='Autosaved'}catch{$('#saved').textContent='Saving unavailable'}}
function choose(type){pendingPlacement=null;world.previewTowers=null;world.range.visible=false;build=type;selected=null;detailKey='';render();beep(300)}
let world;try{world=new World($('#scene'),p=>{if(paused||game.lost||game.won)return;const t=game.towers.find(t=>t.x===p.x&&t.z===p.z);if(t){pendingPlacement=null;selected=t.id;build=null;detailKey='';render();world.showHover(p,null,game,t);return}if(build&&mobileQuery.matches){if(p.x<0||p.x>=13||p.z<0||p.z>=9)return;pendingPlacement={...p,type:build};world.showHover(p,build,game,null);render();return}if(build){const err=game.place(build,p.x,p.z);if(err)toast(err);else{beep(500);persist();render()}}else{selected=null;detailKey='';render()}},p=>world.showHover(p,build,game,game.towers.find(t=>t.id===selected)))}catch(e){$('#scene').innerHTML='<div style="padding:35px">This garden needs WebGL. Enable hardware acceleration in your browser and reload.</div>';throw e}
let detailKey='';
function defenseStats(st,type){return type==='hedge'?'':`<div class="defense-stats"><span><b>${Math.round(st.damage)}</b>Damage / hit</span><span><b>${st.range.toFixed(1)}</b>Range · squares</span><span><b>${st.rate.toFixed(2)}s</b>Between shots</span></div>`}
function renderDetail(){const t=game.towers.find(t=>t.id===selected),d=TOWERS[t?.type||build||'thorn'];const key=JSON.stringify([t?.id,t?.level,t?.branch,build,mobileQuery.matches]);if(key===detailKey)return;detailKey=key;
 $('#detail').hidden=!t&&(!build||mobileQuery.matches);if(!t){
 if(!build||mobileQuery.matches){$('#detail').innerHTML='';return}
 const st=game.stats({type:build,level:1});$('#detail').innerHTML=`<div class="eyebrow">${build==='hedge'?'Maze building':'Before you build'}</div><div class="detail-title"><span class="tower-icon" style="--tile:${d.color}">${d.symbol}</span><h2>${d.name}</h2></div><p class="defense-effect">${d.effect}</p>${defenseStats(st,build)}<p class="defense-tip">${d.tip}</p>`;return
 }
 const st=game.stats(t),c=game.upgradeCost(t);$('#detail').innerHTML=`<button class="detail-close mobile-only" id="close-detail" aria-label="Close tower details">×</button><div class="eyebrow">Level ${t.level}${t.branch?' · '+t.branch:''}</div><div class="detail-title"><span class="tower-icon" style="--tile:${d.color}">${d.symbol}</span><h2>${d.name}</h2></div><p class="defense-effect">${d.effect}</p>${defenseStats(st,t.type)}<p class="defense-tip">${d.tip}</p>${t.level<3&&t.type!=='hedge'?`<p>Upgrade · ${c.coins} coins${MATERIALS.filter(m=>c[m.id]).map(m=>` · ${c[m.id]} ${m.name.toLowerCase()}`).join('')}</p><div class="upgrade-row"><button data-upgrade="power">${t.level===1?'Power +45%':'Grow to level 3'}</button>${t.level===1?'<button data-upgrade="reach">Range +1.1</button>':''}</div>`:'<p>Fully upgraded.</p>'}<button class="text-button" id="sell">Reclaim · ${Math.floor(t.spent*.7)} coins</button>`;
 $('#close-detail')?.addEventListener('click',()=>{selected=null;detailKey='';world.range.visible=false;render()});
 $('#detail').querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{const err=game.upgrade(t.id,b.dataset.upgrade);toast(err||'A little stronger. A little wilder.');detailKey='';persist();render()});$('#sell').onclick=()=>{world.range.visible=false;game.sell(t.id);selected=null;detailKey='';persist();render()};}
let farmKey='';function render(){for(const k of['coins',...MATERIALS.map(m=>m.id)])$('#'+k).textContent=Math.floor(game[k]);$('#lives').textContent=`${game.lives} / 20`;$('#stage-number').textContent=String(Math.min(10,game.stage+1)).padStart(2,'0');$('#wave-counter').textContent=`Wave ${Math.min(3,game.wave+(game.active?0:1))} / 3`;$('#enemy-counter').textContent=game.active?`${game.enemies.length+game.queue.length} remaining`:`${7+game.stage*2+(game.wave+1)*2} creatures`;$('#start').disabled=(game.active&&!paused)||game.lost||game.won;$('#start').textContent=game.won?'Garden protected ✓':game.lost?'Expedition ended':game.active?(paused?'Resume wave ▶':'Wave in progress…'):'Begin wave ↗';document.querySelectorAll('.wave-progress span').forEach((e,i)=>e.classList.toggle('done',i<game.wave));document.querySelectorAll('.stage-dot').forEach((e,i)=>{e.classList.toggle('current',i===game.stage);e.classList.toggle('complete',i<game.stage)});document.querySelectorAll('[data-build]').forEach(b=>{b.classList.toggle('selected',b.dataset.build===build);b.setAttribute('aria-pressed',String(b.dataset.build===build))});$('#paused').hidden=!paused;$('#pause').textContent=paused?'▶':'Ⅱ';$('#speed').textContent=speed+'×';
 $('#placement').hidden=!pendingPlacement;if(pendingPlacement)$('#confirm-place').textContent=`Place ${TOWERS[pendingPlacement.type].name} · ◈ ${TOWERS[pendingPlacement.type].cost}`;renderGarden();renderDetail();}
function renderGarden(){
 const summaryKey=JSON.stringify([game.unlockedPlots,game.farms.map(f=>!!f),...MATERIALS.map(m=>game[m.id])]);if($('#garden-summary').dataset.key!==summaryKey){$('#garden-summary').dataset.key=summaryKey;$('#garden-summary').innerHTML=MATERIALS.map((m,i)=>`<button data-garden-open="${i}" aria-label="Manage ${m.name.toLowerCase()} garden"><span>${m.name}</span><b>${i>=game.unlockedPlots?'Locked':game.farms[i]?game[m.id]:'Buy · '+m.buy}</b></button>`).join('');$('#garden-summary').querySelectorAll('[data-garden-open]').forEach(b=>b.onclick=()=>{$('#garden-modal').showModal();$('#farms').querySelector(`[data-plot="${b.dataset.gardenOpen}"]`)?.scrollIntoView({block:'nearest'})});}
 const ended=game.lost||game.won;
 const fk=JSON.stringify([game.farms.map(f=>f?{...f,progress:Math.floor(f.progress)}:null),game.unlockedPlots,game.coins,ended]);if(fk===farmKey)return;farmKey=fk;
 $('#farms').innerHTML=MATERIALS.map((m,i)=>{
 const f=game.farms[i],locked=i>=game.unlockedPlots,next=i===game.unlockedPlots&&!!game.farms[i-1],cost=locked?m.unlock:game.farmCost(i);
 const disabled=ended||game.coins<cost||(locked&&!next)||f?.level>=3;
 const status=locked?'Locked':f?`Level ${f.level} · +${m.yield*f.level} / 10 sec`:'Not producing';
 const label=locked?`Unlock · ◈ ${cost}`:f?f.level>=3?'Fully upgraded':`Upgrade · ◈ ${cost}`:`Buy ${m.name.toLowerCase()} · ◈ ${cost}`;
 return `<article class="resource-plot ${locked?'locked':''}" data-plot="${i}"><div class="plot-summary"><div class="material-art ${m.id} ${f?'producing':''}" aria-hidden="true"><i></i><i></i><i></i></div><div><b>${m.name}</b><small>${status}</small></div></div><div class="progress"><i style="width:${f?f.progress*10:0}%"></i></div><button ${locked?`data-unlock="${i}"`:`data-farm="${i}"`} ${disabled?'disabled':''} title="${locked&&!next?'Buy '+MATERIALS[i-1].name.toLowerCase()+' first':f&&f.level<3?'Increase production to '+m.yield*(f.level+1)+' every 10 seconds':label}">${label}</button></article>`;
 }).join('');
 $('#farms').querySelectorAll('[data-farm]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.farm),existing=!!game.farms[i],err=game.farm(i);toast(err||(existing?MATERIALS[i].name+' production upgraded.':MATERIALS[i].name+' production started. Materials collect automatically.'));persist();render()});
 $('#farms').querySelectorAll('[data-unlock]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.unlock);toast(game.unlockPlot(i)||MATERIALS[i].name+' plot unlocked. Buy it to start production.');persist();render()});
}

function modal(title,body,button='Back to the garden',action){const m=$('#modal');m.innerHTML=`<div class="eyebrow">Undergrowth</div><h2>${title}</h2><p>${body}</p><button class="primary" id="modal-ok">${button}</button>${action?'<button class="outline" id="modal-cancel">Keep this garden</button>':''}`;const wasPaused=paused;paused=true;render();m.showModal();const close=()=>{m.close();paused=wasPaused;render()};$('#modal-ok').onclick=()=>{close();action?.()};if(action)$('#modal-cancel').onclick=close;m.oncancel=()=>{paused=wasPaused;render()};}
$('#help').onclick=()=>modal('Small pieces. Big possibilities.','<b>1. Shape the maze.</b> Choose a tower, then click a meadow square. The dotted line shows the horde’s route. Keep an exit open.<br><br><b>2. Grow while you defend.</b> Buy the wood plot for 25 coins. It automatically adds 3 wood every 10 seconds, including during combat. Upgrade it with coins for more output. Unlock and buy Rock, then Iron, then Diamond plots with coins. Materials pay for tower upgrades.<br><br><b>3. Put down roots.</b> Survive three waves per stage, across ten stages. Your maze and garden stay. Moths fly over the maze; sunstones pierce armor.<br><br><b>Controls:</b> 1–5 choose pieces, Esc inspects, Space pauses. Progress saves automatically on this browser.');
$('#mobile-options').onclick=()=>{modal('Game menu','<button class="outline" id="menu-help">How to play</button><button class="outline" id="menu-sound">Toggle sound</button><button class="outline" id="menu-restart">New garden</button>','Return to game');for(const name of ['help','sound','restart'])$('#menu-'+name).onclick=()=>{$('#modal-ok').click();$('#'+name).click()}};
$('#close-garden').onclick=()=>$('#garden-modal').close();
$('#garden-modal').addEventListener('click',e=>{if(e.target===$('#garden-modal')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
function cancelPlacement(){pendingPlacement=null;world.previewTowers=null;world.hover.visible=false;world.range.visible=false;render()}
$('#cancel-place').onclick=cancelPlacement;
$('#confirm-place').onclick=()=>{if(!pendingPlacement||paused||game.lost||game.won)return;const p=pendingPlacement,err=game.place(p.type,p.x,p.z);if(err){toast(err);return}cancelPlacement();beep(500);persist()};
$('#zoom').onclick=()=>{world.zoom=Math.min(2.5,world.zoom+.5);world.resize()};
$('#fit').onclick=()=>{world.zoom=1;world.target.set(6,0,4);world.resize();cancelPlacement()};
function adaptLayout(){if(!mobileQuery.matches&&$('#garden-modal').open)$('#garden-modal').close();(mobileQuery.matches?$('#garden-modal .sheet-body'):$('.garden-strip')).append($('#farms'));world.resize();cancelPlacement()}
mobileQuery.addEventListener('change',adaptLayout);adaptLayout();
$('#restart').onclick=()=>modal('Plant a new beginning?','This replaces your saved settlement with a fresh garden. Your current towers and materials will be cleared.','Start a new garden',()=>{pendingPlacement=null;game=new Game();selected=null;build='thorn';paused=false;farmKey='';detailKey='';persist();render();toast('A new beginning. Make it yours.')});
$('#start').onclick=()=>{paused=false;backgroundPause=null;last=performance.now();if(game.active){render();return}if(game.start()){toast('Wave started. Follow the dotted route.');beep(250);persist()}render()};
$('#pause').onclick=()=>{paused=!paused;render()};$('#speed').onclick=()=>{speed=speed===1?2:speed===2?3:1;render()};$('#sound').onclick=()=>{sound=!sound;$('#sound').style.background=sound?'#dce8cb':'transparent';$('#sound').setAttribute('aria-label',sound?'Mute sound':'Enable sound');beep(600)};$('#path').onclick=()=>{world.route.visible=!world.route.visible;$('#path').textContent=world.route.visible?'Route on':'Route off';$('#path').setAttribute('aria-pressed',String(world.route.visible))};
 document.querySelectorAll('[data-build]').forEach(b=>b.onclick=()=>choose(b.dataset.build));window.addEventListener('keydown',e=>{if($('#modal').open||$('#garden-modal').open||e.target.matches('input,textarea,select'))return;if(e.code==='Space'){e.preventDefault();paused=!paused;render()}if('12345'.includes(e.key))choose(Object.keys(TOWERS)[Number(e.key)-1]);if(e.key==='Escape'){pendingPlacement=null;build=null;selected=null;detailKey='';world.range.visible=false;world.hover.visible=false;world.previewTowers=null;render()}});window.addEventListener('pagehide',persist);document.addEventListener('visibilitychange',()=>{if(document.hidden){backgroundPause??=paused;paused=true;persist()}else if(backgroundPause!==null){paused=backgroundPause;backgroundPause=null;last=performance.now()}render()});
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!paused&&!$('#modal').open){let remaining=dt*speed;while(remaining>0){const step=Math.min(remaining,1/30);game.tick(step);remaining-=step}}world.sync(game,dt);for(const ev of game.events){if(ev.type==='wave'){toast('Wave survived. Coins earned. Time to tend your garden.');beep(800)}if(ev.type==='stage'){toast(`Stage ${game.stage+1}: ${STAGES[game.stage][0]}. Your settlement carries on.`)}if(ev.type==='leak')beep(140);if(ev.type==='won')modal('You grew something extraordinary.','Ten stages survived. The wilds are quiet, and your little garden stands. Try a new layout with a fresh expedition.');if(ev.type==='lost')modal('Even gardens need another season.','The horde reached your heart. Start a new garden with the ↺ button. Try a longer maze, early farm upgrades, and Sap beside your damage towers.')}game.events=[];uiTime+=dt;saveTime+=dt;if(uiTime>.15){render();uiTime=0}if(saveTime>3){persist();saveTime=0}requestAnimationFrame(frame)}
render();requestAnimationFrame(frame);
if(import.meta.env.DEV)window.__garden={get game(){return game},world,step(seconds){for(let i=0;i<seconds*30;i++)game.tick(1/30);render()},save:persist};
