import * as THREE from 'three';
import {TOWERS,path} from './game.js';
export class World{
 constructor(container,onCell,onHover){this.container=container;this.onCell=onCell;this.onHover=onHover;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#dce4ce');this.renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});this.renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(pointer: coarse)').matches?1.5:2));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=THREE.PCFSoftShadowMap;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.setClearColor('#dce4ce');container.prepend(this.renderer.domElement);this.camera=new THREE.OrthographicCamera();this.camera.position.set(18,25,25);this.target=new THREE.Vector3(6,0,4);this.camera.lookAt(this.target);this.scene.add(new THREE.HemisphereLight('#fff9df','#788d66',1.8));const sun=new THREE.DirectionalLight('#fff6df',2.4);sun.position.set(-7,20,8);sun.castShadow=true;sun.shadow.mapSize.set(matchMedia('(pointer: coarse)').matches?1024:2048,matchMedia('(pointer: coarse)').matches?1024:2048);Object.assign(sun.shadow.camera,{left:-23,right:23,top:23,bottom:-23,near:.1,far:70});sun.shadow.bias=-.0004;sun.shadow.normalBias=.03;this.scene.add(sun);this.materials=new Map();this.towerMeshes=new Map();this.enemyMeshes=new Map();this.effects=[];this.board=new THREE.Group();this.scene.add(this.board);this.farmGroup=new THREE.Group();this.scene.add(this.farmGroup);this.route=new THREE.Group();this.scene.add(this.route);this.buildWorld();this.ray=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.ground=new THREE.Plane(new THREE.Vector3(0,1,0),0);this.hover=this.box(.94,.045,.94,'#b7d486',this.scene,0,.075,0);this.hover.visible=false;this.range=new THREE.Mesh(new THREE.RingGeometry(.97,1,64),new THREE.MeshBasicMaterial({color:'#f5f5ce',transparent:true,opacity:.65,side:THREE.DoubleSide}));this.range.rotation.x=-Math.PI/2;this.range.position.y=.09;this.range.visible=false;this.scene.add(this.range);this.zoom=1;this.top=true;
 const pick=e=>{const r=this.renderer.domElement.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const p=new THREE.Vector3();this.ray.ray.intersectPlane(this.ground,p);return{x:Math.round(p.x),z:Math.round(p.z)}};
 const pointers=new Map();let gesture=false,pinchDistance=0,lastPan=null;
 const canvas=this.renderer.domElement;
 canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;canvas.setPointerCapture(e.pointerId);pointers.set(e.pointerId,{x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY});if(pointers.size===1){gesture=false;lastPan={x:e.clientX,y:e.clientY}}else{gesture=true;const [a,b]=[...pointers.values()];pinchDistance=Math.hypot(a.x-b.x,a.y-b.y)}});
 canvas.addEventListener('pointermove',e=>{const p=pointers.get(e.pointerId);if(p){p.x=e.clientX;p.y=e.clientY;if(Math.hypot(p.x-p.startX,p.y-p.startY)>8)gesture=true;if(pointers.size===2){const[a,b]=[...pointers.values()],distance=Math.hypot(a.x-b.x,a.y-b.y);if(pinchDistance>0){this.zoom=THREE.MathUtils.clamp(this.zoom*distance/pinchDistance,1,2.5);this.resize()}pinchDistance=distance;lastPan=null;}else if(gesture&&this.zoom>1&&lastPan){const scale=(this.camera.right-this.camera.left)/canvas.clientWidth;const right=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,0),up=new THREE.Vector3().setFromMatrixColumn(this.camera.matrixWorld,1);this.target.addScaledVector(right,-(p.x-lastPan.x)*scale).addScaledVector(up,(p.y-lastPan.y)*scale);this.target.x=THREE.MathUtils.clamp(this.target.x,0,12);this.target.z=THREE.MathUtils.clamp(this.target.z,0,8);this.resize()}lastPan={x:p.x,y:p.y};}if(!gesture)this.onHover(pick(e));});
 canvas.addEventListener('pointerup',e=>{const wasGesture=gesture;pointers.delete(e.pointerId);if(!wasGesture)this.onCell(pick(e));if(!pointers.size){gesture=false;lastPan=null;pinchDistance=0}});
 canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=true;lastPan=null});
 canvas.addEventListener('pointerleave',()=>{this.hover.visible=false;this.previewTowers=null});
 this.resizeObserver=new ResizeObserver(()=>{cancelAnimationFrame(this.resizeFrame);this.resizeFrame=requestAnimationFrame(()=>this.resize())});this.resizeObserver.observe(container);this.resize();}
 mat(color){if(!this.materials.has(color))this.materials.set(color,new THREE.MeshStandardMaterial({color,roughness:.85}));return this.materials.get(color)}
 mesh(geo,color,parent,x=0,y=0,z=0){const m=new THREE.Mesh(geo,this.mat(color));m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 box(w,h,d,c,p,x=0,y=0,z=0){return this.mesh(new THREE.BoxGeometry(w,h,d),c,p,x,y,z)}
 sphere(r,c,p,x,y,z){return this.mesh(new THREE.IcosahedronGeometry(r,1),c,p,x,y,z)}
 cylinder(r1,r2,h,c,p,x,y,z,n=8){return this.mesh(new THREE.CylinderGeometry(r1,r2,h,n),c,p,x,y,z)}
 buildWorld(){this.box(200,.2,200,'#dce4ce',this.board,0,-1.4,0);this.box(14.2,.75,10.2,'#8b9b6d',this.board,6,-.6,4);this.box(14.35,.15,10.35,'#a4b581',this.board,6,-.2,4);this.box(13.5,.16,9.5,'#c0ce9e',this.board,6,-.07,4);
 for(let x=0;x<13;x++)for(let z=0;z<9;z++){const colors=['#c4d2a9','#bdcca0','#c1d0a4','#c8d5ae'];this.box(.963,.055,.963,colors[(x*7+z*11)%4],this.board,x,.025,z)}
 // The heart tree at the exit.
 this.cylinder(.16,.25,1.7,'#8b7750',this.board,13.05,.8,4);for(const [x,y,z,r]of[[13,1.9,4,.75],[12.6,1.6,4.15,.5],[13.45,1.65,4,.55]])this.sphere(r,'#729a61',this.board,x,y,z);this.sphere(.28,'#e5c86b',this.board,13,1.5,4.5);
 for(const z of[3.3,4.7]){this.box(.3,.8,.3,'#e6dcc0',this.board,-.67,.3,z);this.sphere(.16,'#d6aa66',this.board,-.67,.84,z)}
 // Deterministic landscaping, kept clear of clickable tiles.
 let seed=17;const rand=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
 for(let i=0;i<48;i++){const x=-.4+rand()*13,z=i%2?-.82:8.85;const r=.13+rand()*.18;this.sphere(r,['#87a16a','#91ab70','#a1b97b'][i%3],this.board,x,.11,z);if(i%5===0){this.cylinder(.025,.03,.28,'#83965e',this.board,x,.2,z);this.sphere(.09,i%3?'#eee1af':'#d5a08a',this.board,x,.38,z)}}
 for(const [x,z]of[[-1.2,-.5],[13.2,8.9],[-1.3,8.5]]){this.cylinder(.13,.21,1,'#8f7952',this.board,x,.4,z);this.sphere(.65,'#8da876',this.board,x,1.25,z);this.sphere(.45,'#9ab47d',this.board,x+.2,1.7,z)}
 for(let i=0;i<7;i++)this.sphere(.18+rand()*.1,'#b5b69a',this.board,rand()*12,-.03,i%2?9.1:-1.1);
 }
 makeTower(t){const g=new THREE.Group();g.position.set(t.x,0,t.z);this.scene.add(g);this.box(.84,.22,.84,'#ede3c6',g,0,.15,0);this.box(.69,.11,.69,'#9eaa7e',g,0,.32,0);const c=TOWERS[t.type].color;const head=new THREE.Group();g.add(head);g.userData.head=head;
 if(t.type==='hedge'){this.box(.78,.6,.78,c,g,0,.52,0);this.box(.61,.16,.61,'#9ab77b',g,.02,.9,0)}
 if(t.type==='thorn'){this.box(.44,.48,.44,'#b49c6b',head,0,.57,0);this.cylinder(.31,.37,.19,c,head,0,.87,0);this.box(.15,.15,.68,'#405e48',head,0,.93,.24);this.sphere(.1,'#e3d49b',head,0,1.01,-.12)}
 if(t.type==='sap'){this.cylinder(.3,.36,.45,'#6e9d8d',head,0,.58,0);this.sphere(.29,c,head,0,.96,0);this.cylinder(.055,.08,.45,'#e2d4a3',head,0,1.25,0);this.sphere(.11,'#c3e3b5',head,0,1.5,0)}
 if(t.type==='bloom'){this.cylinder(.12,.19,.55,'#779862',head,0,.57,0);for(let i=0;i<5;i++){let a=i*Math.PI*2/5;this.sphere(.22,c,head,Math.cos(a)*.23,.95,Math.sin(a)*.23)}this.sphere(.2,'#efd899',head,0,1.05,0)}
 if(t.type==='prism'){this.box(.4,.5,.4,'#9b94ad',head,0,.58,0);this.mesh(new THREE.OctahedronGeometry(.34),'#c4b9e4',head,0,1.12,0);this.cylinder(.3,.3,.06,'#e8d79f',head,0,.84,0)}
 for(let i=1;i<t.level;i++)this.box(.12,.06,.12,'#f0cf76',g,-.23+(i-1)*.23,.29,.42);g.userData.level=t.level;g.userData.type=t.type;return g}
 disposeGroup(g){g.traverse(o=>{if(o.geometry)o.geometry.dispose();});g.removeFromParent()}
 setPath(towers){const key=towers.map(t=>`${t.x},${t.z}`).join(';');if(key===this.pathKey)return;this.pathKey=key;for(const c of[...this.route.children])this.disposeGroup(c);const points=path(towers)||[];for(let i=0;i<points.length-1;i++){const a=points[i],b=points[i+1];for(let k=0;k<3;k++)this.cylinder(.037,.037,.016,'#7d9569',this.route,a.x+(b.x-a.x)*k/3,.071,a.z+(b.z-a.z)*k/3,6)}}
 showHover(p,type,game,selected){this.previewTowers=null;const valid=p.x>=0&&p.x<13&&p.z>=0&&p.z<9;this.hover.visible=valid&&!!type;if(valid){this.hover.position.set(p.x,.08,p.z);const blocked=game.towers.some(t=>t.x===p.x&&t.z===p.z)||!path([...game.towers,{x:p.x,z:p.z}])||((p.x===0||p.x===12)&&p.z===4);this.hover.material=this.mat(blocked?'#cc8875':'#e1edba');if(type&&!blocked)this.previewTowers=[...game.towers,{x:p.x,z:p.z}]}
 const t=selected|| (valid&&type?{type,x:p.x,z:p.z,level:1}:null);this.range.visible=!!t&&t.type!=='hedge';if(t){const r=game.stats(t).range;this.range.scale.set(r,r,1);this.range.position.set(t.x,.09,t.z)}}
 sync(game,dt){this.setPath(this.previewTowers||game.towers);for(const[id,g]of this.towerMeshes){if(!game.towers.some(t=>t.id===id&&t.level===g.userData.level)){this.disposeGroup(g);this.towerMeshes.delete(id)}}for(const t of game.towers)if(!this.towerMeshes.has(t.id))this.towerMeshes.set(t.id,this.makeTower(t));
 for(const[id,g]of this.enemyMeshes){if(!game.enemies.some(e=>e.id===id)){this.disposeGroup(g);this.enemyMeshes.delete(id)}}
 for(const e of game.enemies){let g=this.enemyMeshes.get(e.id);if(!g){g=new THREE.Group();this.scene.add(g);const color={grub:'#b87d68',runner:'#d7aa60',armor:'#788798',moth:'#d8cee6',boss:'#7d668b'}[e.kind];const body=this.sphere(e.kind==='boss'?.48:.23,color,g,0,.28,0);body.scale.z=1.25;for(const x of[-.085,.085]){this.sphere(.048,'#fbf3dd',g,x,.37,.22);this.sphere(.024,'#3e4338',g,x,.37,.257)}if(e.flying){for(const x of[-.3,.3]){const wing=this.sphere(.25,'#eae1ec',g,x,.3,0);wing.scale.set(1,.12,1.1)}}else{for(const x of[-.23,.23])for(const z of[-.13,.13])this.box(.14,.07,.07,'#675747',g,x,.14,z)}const bg=this.box(.5,.035,.045,'#6f7260',g,0,.8,0);const hp=this.box(.5,.04,.05,'#d7e7a8',g,0,.8,.005);g.userData.hp=hp;if(e.kind==='boss')g.scale.setScalar(1.5);this.enemyMeshes.set(e.id,g)}g.position.set(e.x,e.flying?.8+Math.sin(game.time*8)*.08:Math.sin(game.time*12+e.id)*.025,e.z);g.userData.hp.scale.x=Math.max(.01,e.hp/e.maxHp);if(e.target)g.rotation.y=Math.atan2(e.target.x-e.x,e.target.z-e.z)}

 for(const ev of game.events){if(ev.type==='shot'){const t=game.towers.find(t=>t.id===ev.tower),g=this.towerMeshes.get(ev.tower);if(!t)continue;if(g)g.userData.head.rotation.y=Math.atan2(ev.x-t.x,ev.z-t.z);const geo=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(t.x,.95,t.z),new THREE.Vector3(ev.x,.4,ev.z)]);const beam=new THREE.Line(geo,new THREE.LineBasicMaterial({color:TOWERS[ev.towerType].color,transparent:true,opacity:.95}));this.scene.add(beam);this.effects.push({mesh:beam,life:.16,max:.16})}if(ev.type==='kill'){for(let i=0;i<5;i++){const m=this.sphere(.07,'#e9d799',this.scene,ev.x,.35,ev.z);this.effects.push({mesh:m,life:.4,max:.4,v:new THREE.Vector3(Math.sin(i*7)*1.5,1.2,Math.cos(i*7)*1.5)})}}}
 for(const f of this.effects){f.life-=dt;if(f.v)f.mesh.position.addScaledVector(f.v,dt);if(f.mesh.isLine)f.mesh.material.opacity=Math.max(0,f.life/f.max);if(f.life<=0){f.mesh.geometry.dispose();if(f.mesh.isLine)f.mesh.material.dispose();f.mesh.removeFromParent()}}this.effects=this.effects.filter(f=>f.life>0);this.renderer.render(this.scene,this.camera)}
 resize(){const w=this.container.clientWidth,h=this.container.clientHeight;this.renderer.setSize(w,h,false);const aspect=w/h;const portrait=matchMedia('(pointer: coarse)').matches&&w<h;const fitAspect=w/Math.max(100,h-(matchMedia('(pointer: coarse)').matches?70:0));const width=Math.max(portrait?11:15.5,(portrait?15.5:11)*fitAspect)/this.zoom;this.camera.left=-width/2;this.camera.right=width/2;this.camera.top=width/aspect/2;this.camera.bottom=-width/aspect/2;this.camera.up.set(portrait?-1:0,0,portrait?0:-1);this.camera.position.copy(this.target).add(new THREE.Vector3(0,30,0));this.camera.lookAt(this.target);this.camera.updateProjectionMatrix()}
 cellScreen(x,z){const p=new THREE.Vector3(x,0,z).project(this.camera),r=this.renderer.domElement.getBoundingClientRect();return{x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}}
}
